import type { Category, Product } from "@/types";

export const categories: Category[] = [
  { id: "all", label: "All Items", icon: "LayoutGrid" },
  { id: "grocery", label: "Grocery & Rice", icon: "Utensils" },
  { id: "oil", label: "Oil & Ghee", icon: "GlassWater" },
  { id: "personal", label: "Personal Care", icon: "Cookie" },
  { id: "snacks", label: "Snacks & Biscuits", icon: "Croissant" },
  { id: "beverages", label: "Beverages", icon: "CupSoda" },
];

export const products: Product[] = [
  {
    id: "prd-miniket-5kg",
    name: "Rice Miniket 5kg",
    description: "Premium aromatic rice",
    price: 350.0,
    categoryId: "grocery",
    emoji: "🌾",
    barcode: "2400153",
    accent: "from-amber-400 to-yellow-600",
    popular: true,
    stock: 120,
  },
  {
    id: "prd-soyabean-1l",
    name: "Fresh Soyabean Oil 1L",
    description: "Refined 100% pure vegetable oil",
    price: 180.0,
    categoryId: "oil",
    emoji: "🍾",
    barcode: "6000132",
    accent: "from-yellow-400 to-amber-500",
    popular: true,
    stock: 95,
  },
  {
    id: "prd-lifebuoy-125g",
    name: "Lifebuoy Soap 125g",
    description: "Total 10 germ protection soap",
    price: 50.0,
    categoryId: "personal",
    emoji: "🧼",
    barcode: "2400165",
    accent: "from-red-500 to-rose-600",
    popular: true,
    stock: 250,
  },
  {
    id: "prd-aarong-butter-200g",
    name: "Aarong Butter 200g",
    description: "Salted creamery butter",
    price: 220.0,
    categoryId: "grocery",
    emoji: "🧈",
    barcode: "2800848",
    accent: "from-amber-300 to-yellow-500",
    stock: 60,
  },
  {
    id: "prd-ruchi-chanachur-150g",
    name: "Ruchi Chanachur 150g",
    description: "Hot & spicy fried snack",
    price: 65.0,
    categoryId: "snacks",
    emoji: "🥨",
    barcode: "2900434",
    accent: "from-orange-500 to-red-600",
    popular: true,
    stock: 180,
  },
  {
    id: "prd-pran-turmeric-100g",
    name: "Pran Turmeric Powder 100g",
    description: "Pure ground turmeric spice",
    price: 85.0,
    categoryId: "grocery",
    emoji: "🧂",
    barcode: "2900312",
    accent: "from-yellow-500 to-amber-600",
    stock: 90,
  },
  {
    id: "prd-teer-atta-2kg",
    name: "Teer Whole Wheat Atta 2kg",
    description: "100% whole wheat flour",
    price: 140.0,
    categoryId: "grocery",
    emoji: "🥖",
    barcode: "3002543",
    accent: "from-stone-400 to-amber-600",
    stock: 80,
  },
  {
    id: "prd-pusti-sugar-1kg",
    name: "Pusti Refined Sugar 1kg",
    description: "White refined crystal sugar",
    price: 135.0,
    categoryId: "grocery",
    emoji: "🍧",
    barcode: "2400154",
    accent: "from-slate-200 to-slate-400",
    stock: 110,
  },
  {
    id: "prd-horlicks-500g",
    name: "Horlicks Jar 500g",
    description: "Nourishing malted drink powder",
    price: 480.0,
    categoryId: "beverages",
    emoji: "🏺",
    barcode: "6000140",
    accent: "from-blue-500 to-indigo-600",
    stock: 45,
  },
  {
    id: "prd-nescafe-50g",
    name: "Nescafe Classic 50g",
    description: "100% pure instant coffee",
    price: 260.0,
    categoryId: "beverages",
    emoji: "☕",
    barcode: "6000023",
    accent: "from-amber-700 to-stone-800",
    stock: 70,
  },
];