import type { Category, Product } from "@/types";

export const categories: Category[] = [
  { id: "all", label: "All Items", icon: "LayoutGrid" },
  { id: "coffee", label: "Coffee", icon: "Coffee" },
  { id: "tea", label: "Tea", icon: "CupSoda" },
  { id: "bakery", label: "Bakery", icon: "Croissant" },
  { id: "meals", label: "Meals", icon: "Utensils" },
  { id: "snacks", label: "Snacks", icon: "Cookie" },
  { id: "beverages", label: "Beverages", icon: "GlassWater" },
];

export const products: Product[] = [
  {
    id: "prd-espresso",
    name: "Espresso",
    description: "Single shot, rich & bold",
    price: 2.5,
    categoryId: "coffee",
    emoji: "☕",
    accent: "from-amber-500 to-orange-600",
    popular: true,
    stock: 120,
  },
  {
    id: "prd-latte",
    name: "Caffe Latte",
    description: "Espresso with steamed milk",
    price: 4.2,
    categoryId: "coffee",
    emoji: "🥛",
    accent: "from-yellow-400 to-amber-500",
    popular: true,
    stock: 90,
  },
  {
    id: "prd-cappuccino",
    name: "Cappuccino",
    description: "Espresso, milk & foam",
    price: 3.8,
    categoryId: "coffee",
    emoji: "🍮",
    accent: "from-orange-400 to-rose-500",
    stock: 85,
  },
  {
    id: "prd-mocha",
    name: "Mocha",
    description: "Espresso, chocolate & milk",
    price: 4.6,
    categoryId: "coffee",
    emoji: "🍫",
    accent: "from-rose-500 to-red-600",
    popular: true,
    stock: 70,
  },
  {
    id: "prd-matcha",
    name: "Matcha Latte",
    description: "Ceremonial matcha & milk",
    price: 4.9,
    categoryId: "tea",
    emoji: "🍵",
    accent: "from-green-500 to-emerald-600",
    stock: 60,
  },
  {
    id: "prd-earl-grey",
    name: "Earl Grey",
    description: "Black tea with bergamot",
    price: 3.1,
    categoryId: "tea",
    emoji: "🫖",
    accent: "from-slate-400 to-slate-600",
    stock: 75,
  },
  {
    id: "prd-croissant",
    name: "Butter Croissant",
    description: "Flaky, golden & warm",
    price: 3.5,
    categoryId: "bakery",
    emoji: "🥐",
    accent: "from-yellow-500 to-amber-700",
    popular: true,
    stock: 40,
  },
  {
    id: "prd-cinnamon",
    name: "Cinnamon Roll",
    description: "With cream cheese glaze",
    price: 4.4,
    categoryId: "bakery",
    emoji: "🥨",
    accent: "from-orange-500 to-red-700",
    stock: 32,
  },
  {
    id: "prd-banana-bread",
    name: "Banana Bread",
    description: "Slice, house recipe",
    price: 3.9,
    categoryId: "bakery",
    emoji: "🍌",
    accent: "from-amber-400 to-yellow-600",
    stock: 28,
  },
  {
    id: "prd-bagel",
    name: "Everything Bagel",
    description: "Toasted with cream cheese",
    price: 4.0,
    categoryId: "bakery",
    emoji: "🥯",
    accent: "from-stone-400 to-stone-600",
    stock: 36,
  },
  {
    id: "prd-pancakes",
    name: "Buttermilk Pancakes",
    description: "Stack with maple syrup",
    price: 8.9,
    categoryId: "meals",
    emoji: "🥞",
    accent: "from-rose-400 to-orange-500",
    popular: true,
    stock: 22,
  },
  {
    id: "prd-avocado-toast",
    name: "Avocado Toast",
    description: "Sourdough, chili flakes",
    price: 7.5,
    categoryId: "meals",
    emoji: "🥑",
    accent: "from-lime-500 to-green-700",
    stock: 25,
  },
  {
    id: "prd-club-sandwich",
    name: "Club Sandwich",
    description: "Triple decker, fries",
    price: 9.8,
    categoryId: "meals",
    emoji: "🥪",
    accent: "from-amber-500 to-orange-700",
    stock: 18,
  },
  {
    id: "prd-caesar-salad",
    name: "Caesar Salad",
    description: "Crisp romaine, parmesan",
    price: 8.2,
    categoryId: "meals",
    emoji: "🥗",
    accent: "from-green-500 to-teal-600",
    stock: 20,
  },
  {
    id: "prd-cookies",
    name: "Choc Chip Cookies",
    description: "Baked fresh daily",
    price: 2.2,
    categoryId: "snacks",
    emoji: "🍪",
    accent: "from-amber-600 to-brown-700",
    popular: true,
    stock: 150,
  },
  {
    id: "prd-muffin",
    name: "Blueberry Muffin",
    description: "Tender crumb",
    price: 3.2,
    categoryId: "snacks",
    emoji: "🧁",
    accent: "from-indigo-400 to-purple-600",
    stock: 44,
  },
  {
    id: "prd-fries",
    name: "Loaded Fries",
    description: "Cheese & herbs",
    price: 5.5,
    categoryId: "snacks",
    emoji: "🍟",
    accent: "from-yellow-400 to-amber-600",
    stock: 60,
  },
  {
    id: "prd-fruit-salad",
    name: "Fruit Cup",
    description: "Seasonal fresh fruit",
    price: 4.8,
    categoryId: "snacks",
    emoji: "🍓",
    accent: "from-rose-400 to-fuchsia-500",
    stock: 30,
  },
  {
    id: "prd-cola",
    name: "Cola (Can)",
    description: "Ice cold",
    price: 1.8,
    categoryId: "beverages",
    emoji: "🥤",
    accent: "from-red-500 to-red-700",
    stock: 200,
  },
  {
    id: "prd-orange-juice",
    name: "Fresh Orange Juice",
    description: "Squeezed to order",
    price: 4.3,
    categoryId: "beverages",
    emoji: "🍊",
    accent: "from-orange-400 to-yellow-500",
    popular: true,
    stock: 48,
  },
  {
    id: "prd-mineral-water",
    name: "Mineral Water",
    description: "Still, 500ml",
    price: 1.5,
    categoryId: "beverages",
    emoji: "💧",
    accent: "from-sky-400 to-blue-600",
    stock: 300,
  },
  {
    id: "prd-lemonade",
    name: "Lemonade",
    description: "Freshly pressed",
    price: 3.6,
    categoryId: "beverages",
    emoji: "🍋",
    accent: "from-lime-400 to-yellow-500",
    stock: 55,
  },
];